org.gradle.jvmargs=-Xmx3G

gpr.username=dragoni7
gpr.token=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

# Mod properties
mod_name=SilentCompat
mod_id=silentcompat
mod_license=MIT
mod_version=1.5.0
mod_group_id =com.github.dragoni7
mod_description=Compat and additions for SilentGear
mod_authors=dragoni7
issue_tracker_url=https://github.com/dragoni7/Silent-Compat/issues
display_url=https://github.com/dragoni7/Silent-Compat/blob/1.21.x/README.md

# Env properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.2)
neo_version=21.1.45
neo_version_range=[21,)
loader_version_range=[4,)

## Dependencies
jei_version=19.+
emi_version=1.1+
silentlib_version=10.3+
silentlib_version_range=[10,)
silentgear_version=4.+
silentgear_version_range=[4.0.8,)
botania_version=1.20.1-443-FORGE
